base:
  project: Assignee

data_path:
  train:
    train_canon: data\train\canon\
    train_raw: data\train\huawei_raw\
  test:
    test_canon: data\test\canon\
    test_raw: data\test\huawei_raw\
    test_full: data\test\huawei_full_resolution\
    test_visualized: data\test\huawei_visualized\

data_load:
  PATCH_WIDTH: 224
  PATCH_HEIGHT: 224
  BATCH_SIZE: 32
  TRAIN_SIZE: 30000

train:
  level_iter: [5000, 5000, 20000, 20000, 35000, 100000]

model_dir: [modelL0, modelL1, modelL2, modelL3, modelL4, modelL5]

vgg:
  vgg_dir: vgg\vgg.mat